# Generated by Django 4.1.7 on 2023-03-24 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='address',
            new_name='education',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='state',
            new_name='experience',
        ),
        migrations.RemoveField(
            model_name='record',
            name='zipCode',
        ),
        migrations.AddField(
            model_name='record',
            name='skills',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
