# Generated by Django 4.1.7 on 2023-03-24 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_actions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actions',
            old_name='user',
            new_name='username',
        ),
    ]
