# Generated by Django 4.1.7 on 2023-03-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_user_actions_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
