# Generated by Django 4.1.7 on 2023-03-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_actions_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='profilePic',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
