# Generated by Django 4.1.7 on 2023-03-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_record_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='profilePic',
        ),
        migrations.AddField(
            model_name='record',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
